service: project-catalog-backend
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'
