service: project-catalog-backend
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  timeout: 5
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*' # Allows all S3 actions
      Resource: 'arn:aws:s3:::project-catalog-storage/*' # All objects in this bucket
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*' # Allows all DynamoDB actions
      Resource:
        - 'arn:aws:dynamodb:us-east-2:228073560233:table/ArticlesPublished'
        - 'arn:aws:dynamodb:us-east-2:228073560233:table/ArticlesPublished/index/*'
        - 'arn:aws:dynamodb:us-east-2:228073560233:table/ArticlesUnpublished'
        - 'arn:aws:dynamodb:us-east-2:228073560233:table/ArticlesUnpublished/index/*'
        - 'arn:aws:dynamodb:us-east-2:228073560233:table/Users'
        - 'arn:aws:dynamodb:us-east-2:228073560233:table/Users/index/*'
        - 'arn:aws:dynamodb:us-east-2:228073560233:table/Tokens'
        - 'arn:aws:dynamodb:us-east-2:228073560233:table/Tokens/index/*'
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
        - 'ses:SendRawEmail'
      Resource:
        - 'arn:aws:ses:us-east-2:228073560233:identity/projectcatalog.click'
        - 'arn:aws:ses:us-east-2:228073560233:identity/no-reply@projectcatalog.click'

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any

custom:
  dotenv:
    path: .env.${opt:stage, 'dev'}
  esbuild:
    minify: true
    bundle: true
    target: 'node18'
    sourcemap: true
    packagerOptions:
      scripts:
        - npm install --os=linux --cpu=x64 sharp
    external:
      - sharp
    exclude:
      - aws-sdk
